### ISSUE TITLE
[Question] Pre-filled input

### ISSUE THREAD

**Issue by zagoskin** [pablopioli/BlazorInputMask#2]
Hi! I was just wondering if there's any way to force the mask to be applied. I have a view in which users can navigate to with values that are already filled, but when I do it the input is shown without the mask. Is there some way to "execute" the mask apply manually on the form initialization?

Thanks!

**Comment by pablopioli** [comment]
If you have binded the fomatting is applied on initial display, see the sample named as "Binding". Are you using an unbinded textbox?
